eveseat/web

src/Config/web.permissions.php
src/Http/Routes/Corporation/View.php

update permission list according to their usage in routes
use ledger permission for corporation ledger routes instead of journal permission
impact : people may have to review a few user/roles permissions.

Fix permission issues

---

src/lang/en/seat.php
src/resources/views/corporation/starbase/summary.blade.php

- 72 hours fuel remaining or less : show label in yellow
- 24 hours fuel remaining or less : show label in red

Add two low fuel warning on starbase list

---

src/WebServiceProvider.php

fixing possible issue with Supervisor Monitor setting due to port config type returned as string instead an integer (thanks to gunfighterj)

fixing possible issue with Supervisor Monitor setting

---

src/resources/views/layouts/app-mini.blade.php
src/resources/views/layouts/app.blade.php

Allow a child template to add content to the `<head>` of the main layout by using the `push` directive. Useful to add  a custom css for example :
(example.blade.php)
```
[...]
@push('head')
<link rel="stylesheet" href="{{ asset('a/custom/stylesheet.css') }}">
@endpush

Allow to add custom content from a child template to <head>

---

src/resources/views/people/list.blade.php

I found the feature awesome but hard to navigate and I think this rework is a bit clearer than the current one.
Current : 
After : 
Still no luck with DataTables tho since it does not handle rowspans in the tbody tag.

Improved Tools>People Groups layout

---

src/resources/views/character/skills.blade.php

Quick changes to the blade template to strip every other line and applied format to the sum of the skill points.
Before:
After:

improved lisibility on the skill sheet of a character

---

src/Http/Controllers/Api/KeyController.php

the current delete statement is not firing the delete event from eloquent
therefore, attached characters and key info will never been dropped
https://laravel.com/docs/5.4/eloquent#deleting-models

the current delete statement is not firing the delete event

---

src/resources/views/configuration/users/list.blade.php

Showing account status if no mail activation has been set is a non sense. Therefore, hide it from user list when this parameter is false.
Also add standard account flag.

hide enable/disable account status if no activation mail is enabled

---

src/WebServiceProvider.php
src/resources/views/layouts/app-mini.blade.php
src/resources/views/layouts/app.blade.php

- custom-layout-mini.css is used on login page
- custom-layout.css is used everywhere else
1) create one of the css file or both at the SeAT root directory
2) run `php artisan vendor:publish` in order to publish them
This feature must be used by user and not integrator which can access to header with `head stack`

allow SeAT owner to overload theme using two custom css file

---

src/Acl/AccessChecker.php

Laravel documentation example :
```
$user = App\User::find(1);
foreach ($user->roles as $role) {
//
}
```
Impact API package which was always returning false for user who were not super user

fix hasrole method by calling magic property instead method.

---

src/resources/views/corporation/structures.blade.php

Add a data-sort attribute with the full timestamp in order to fix sort
on offline estimated time.
Closes eveseat/seat#413

fix(corporation structures): Fix table sort on offline column

---

src/resources/views/character/contacts.blade.php
src/resources/views/corporation/contacts.blade.php

Use label_ids field directly as a filter since v2 endpoint is returning an array of ids instead
concatenated binary and.
Closes eveseat/seat#368

feat(contacts): Bump corporation and character contact endpoint to v2

---

src/resources/views/character/sheet.blade.php

Fix character jump clone model relation to target universe structure instead StaStation when
location_type field has a value of structure.
Closes eveseat/seat#397

fix(jump clones): Display name of player structure

---

src/resources/views/corporation/tracking.blade.php

Add missing relation between corporation member tracking to universe structure, station and map
tables.
Provide attributes based on universe structure in order to ensure parity between all three
data source.
Show resolved location name instead location ID and display "Unknown Location" if no match.
Closes eveseat/seat#374

fix(corporation tracking): fix last location column

---

src/Http/Controllers/Character/IndustryController.php
src/Http/Controllers/Corporation/IndustryController.php
src/resources/views/character/industry.blade.php
src/resources/views/corporation/industry.blade.php
src/resources/views/includes/javascript/id-to-name.blade.php

Append table on column definition from both character and corporation industry datatable since
we're using more than a single table in our query. Yajra DT need table.field in order to build
proper query.
Also remove installer column from character industry jobs which is useless.
BREAKING CHANGE: eveseat/web#202

fix(industry jobs): Fix datatable search

---

src/resources/views/character/industry.blade.php

eveseat/web#6e7f0081ce920f5709c14f4c6d91696cd485f98f introduce an error in the way filters were
done. Currently, the job status filter is applied on Product instead Status column.
Closes eveseat/seat#433

fix(character): Address an issue related to filter on industry page

---

src/Http/Controllers/Character/MiningLedgerController.php
src/Http/Controllers/Corporation/MiningLedgerController.php
src/resources/views/character/includes/mining-ledger-modal.blade.php
src/resources/views/character/mining-ledger.blade.php
src/resources/views/corporation/mining/ledger.blade.php
src/resources/views/partials/miningquantity.blade.php
src/resources/views/partials/miningvalue.blade.php
src/resources/views/partials/miningvolume.blade.php

Adapting views to calculate the correct value.
* changed table header from `amount` to `value`
* detailed ledger is now fully server side rendered
* making sure home-tile is still working
* respecting number representation setting
This is step 3 of 3 for resolving: eveseat/seat#341

Mining value

---

src/Http/Controllers/Character/MiningLedgerController.php
src/Http/Controllers/Corporation/MiningLedgerController.php
src/resources/views/character/mining-ledger.blade.php
src/resources/views/corporation/mining/ledger.blade.php
src/resources/views/partials/miningvalue.blade.php

Since last update applied for price updating, every retrieved ledger entry is leading to a load
from historical_price table. On ledger display, it's causing big issues.
depends on eveseat/eveapi#123 and eveseat/services#65

fix(mining ledger): Fix loading time issue due to prices eager-load

---

src/resources/views/corporation/mining/ledger.blade.php

The corporation mining ledger view contains a reference to the variable $character_id for the main character column, which should be $entry->character_id.

fix ErrorException for undefined variable character_id

---

src/Http/Controllers/Support/ResolveController.php

Use existing UniverseNames instead of creating ResolvedIds Model.
This would have impact on the following two PRs:
- ~~https://github.com/eveseat/web/pull/233~~ (removed dependency)
- ~~https://github.com/eveseat/web/pull/227~~ (removed dependency)
f.e. 
https://github.com/eveseat/web/pull/233/files#diff-8b412ff1d63c9ac6479a3bde722c4da5 
would become obsolete and name resolving could be done via already existing 'universe_names' table

Resolve ids universe names

---

src/Http/Controllers/Auth/SsoController.php
src/Http/Controllers/Configuration/UserController.php
src/Models/User.php
src/resources/views/configuration/users/edit.blade.php

When an user is attached to a non existing group, the user list may
crash due to some relation which are returning a null value.
This is reducing coupling for an User model by using directly the group_id from
the user entry and excluding things attached to group when none are
returned (mails, role, etc...).
Closes eveseat/seat#491

fix(users): Reduce user coupling and avoid null exception

---

src/Http/Composers/CharacterLayout.php
src/Http/Controllers/Corporation/TrackingController.php
src/lang/en/seat.php
src/resources/views/configuration/users/list.blade.php
src/resources/views/configuration/users/partials/refresh-token.blade.php
src/resources/views/corporation/partials/refresh-token.blade.php
src/resources/views/corporation/tracking.blade.php

Fix Issue 512 - Corp Tracking shows people who are not in Corporation  …
* Don't show non-corp members in member-tracking
* Remove checkbox
* Introduce tabs: Valid, Invalid and Missing on Seat
this resolves: https://github.com/eveseat/seat/issues/512

Fix issue 512 related to corp tracking

---

src/Http/Composers/CharacterLayout.php
src/lang/en/seat.php

This adds the information about character information that are out of date due to missing refresh token:

Add warning about outdated information.

---

src/WebServiceProvider.php

Due to the way Horizon access is checked, user method may be unset
which will result in a null exception during the access control to the
board.
```
Call to a member function has() on null in
/var/www/seat/packages/eveseat/web/src/WebServiceProvider.php on line
290
```

fix(ACL): Avoid null exception on Horizon access check

---

src/Http/Controllers/Configuration/UserController.php
src/Http/Validation/EditUser.php
src/lang/en/seat.php

Since 3.x, the e-mail address field has been removed from user table and
become an user setting. However, it seems it has not been properly
updated during the migration.
Closes eveseat/seat#493

fix(user): ensure the email address is properly updated

---

src/Models/User.php

SEAT api was changed to include the main character id. This is ensuring the swagger documentation also shows this.

Amending swagger documentation

---

src/resources/views/corporation/security/titles.blade.php

Exploit the new Eloquent Pivot relationship to render the corporation
title page properly and avoid excessive memory consummation.
Closes eveseat/seat#595

fix(titles): reduce abnormal loop on corp titles page

---

composer.json
src/Http/Controllers/Squads/SquadsController.php
src/Http/Scopes/SquadScope.php
src/Models/Squads/Squad.php
src/resources/views/squads/list.blade.php
src/resources/views/squads/show.blade.php

This commit is providing a different layout for squads listing due to recent complaint on Slack.
Previous table has been replaced by a paginated card deck, able to render up to 6 card a time.
For convenient ergonomy, most of controls are javascript based.
- cards got a smooth fade effect while they're appearing
- squad without a proper logo set got a named avatar style generated
- pagination is updated dynamically according to user search
TODO :

refactor(squads): improve list layout with dynamic search

---

src/Acl/AccessChecker.php

this is considered as a non critical bug.
however, due to the issue, it may cause strange behaviour while working with multiple roles getting similar affiliations.
previous way to merge permissions array was only appending permissions with a key which didn't exist in previous array related to the affiliation. As a result, some assigned permissions by a role, targeting an affiliation which was already set by a previous roles may be missing on role members.

fix(cve): this address an issue on affiliations permissions merge

---

src/Events/Login.php

An HTTP 500 error is generated during SSO login if the SeAT user has a refresh token/character with Director roles. The attempt to trigger CorporationTokenShouldUpdate in the Login event needed to be updated to accommodate the changes in commit 80b76dc.
From Laravel log: 
local.ERROR: Argument 1 passed to Seat\Console\Bus\CorporationTokenShouldUpdate::__construct() must be of the type int, object given, called in /var/www/seat/packages/eveseat/web/src/Events/Login.php on line 72 {"userId":47,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Seat\\Console\\Bus\\CorporationTokenShouldUpdate::__construct() must be of the type int, object given, called in /var/www/seat/packages/eveseat/web/src/Events/Login.php on line 72 at …

(fix) update Login event to accomodate changes in Console package.

---

src/database/migrations/2019_11_12_220840_drop_groups_table.php

When a condition that triggers the Exception to be thrown is met, you instead get a different Exception when running the migration as the property $entry->name is undefined. Updated DB query to return the users name column.

(fix) undefined property $entry->name in drop_groups_table migration

---

src/resources/views/character/notification.blade.php

The Accessor on the Character Notifications model parses the Yaml stored in the DB, but returns an array. Trying to access this results in a PHP error parsing the array to string. Also updated the Bootstrap 3 popover component to the new Bootstrap 4 tooltip component.

fix(notifications): fix datatables error on character notifications from issue passing notification text from array to string

---

src/Http/Controllers/Character/IntelController.php
src/Http/Routes/Character/View.php
src/resources/views/character/intel/buttons/journal.blade.php
src/resources/views/character/intel/summary.blade.php

Front-end refactor for eveseat/services#119.
Removes reliance on CharacterAffiliation model as the basis for the query which results in duplicates when dealing with corporation entities (as you get one result for each character that is affiliated to that corp in the model).

refactor(intel): updated to reflect changes to Intel repository in services package

---

src/Http/DataTables/Scopes/KillMailCharacterScope.php
src/Http/DataTables/Scopes/KillMailCorporationScope.php
src/Http/DataTables/Scopes/MiningCorporationScope.php
src/Models/Acl/Role.php
src/Models/User.php

Upgrade API documentation annotation from Swagger (v2.0) to Open API (v3.0)
Main change is related to namespace which has been renamed from `SWG` to `OA`
There is also a replacement for the body parameter which got its own keyword `RequestBody`
Depends: eveseat/api#39 eveseat/eveapi#203

Prepare api package for SeAT 4.0.x

---

src/resources/views/corporation/structures/list.blade.php

Adds name column to the corporation structures table based on the value in the universe structures table.
Closes eveseat/seat#606.

Add name column to corporation structures table

---

src/Events/Login.php
src/Http/Controllers/Auth/SsoController.php
src/Observers/CharacterRoleObserver.php
src/Observers/RefreshTokenObserver.php
src/WebServiceProvider.php

to avoid ESI spam, we will enqueue all character jobs only on first authentication (when token is created). Otherwise, data will be updated using scheduler flow.
for the same reason, we will enqueue all corporation jobs only on character role of type Director creation. Otherwise, data will be updated using scheduler flow.
character affiliation is still updated on each authentication.

Avoid to spam ESI on each auth

---

src/resources/views/search/components/character_assets.blade.php
src/resources/views/search/components/skills.blade.php

in order to make search engine more useful, remove character name, corporation name and alliance name from searched column into assets and skills.

refactor(search): remove entity name from assets and skills search

---

src/Http/Composers/Sidebar.php
src/Http/Controllers/Configuration/SeatController.php
src/Http/Routes/Configuration/Seat.php
src/Http/Validation/Customlink.php
src/resources/lang/en/seat.php
src/resources/views/configuration/settings/view.blade.php
src/resources/views/includes/sidebar.blade.php

This PR closes eveseat/seat#605.
Adds a new option to SeAT settings page to add custom sidebar links. The sidebar links are stored in the global settings database table and are merged into the sidebar menu by the sidebar view composer (which sorts them alphabetically). 
Supports adding any number of links with the option to manually assign the Font Awesome icon class (refer to the Font Awesome site for list of free icons available).

feat(customlink): Initial implementation of custom sidebar links.

---

src/resources/views/configuration/settings/view.blade.php

Adds checkmark UI icon next to SDE version similar to rest of SeAT modules and plugins:
Also includes in version report when copied to clipboard:
```
| Vendor     | Package Name   | Installed Version        |
| ---------- | -------------- | ------------------------ |
| eveseat    | api            | 3.0.8                    |
| eveseat    | console        | 3.0.5                    |
| eveseat    | eveapi         | 3.0.17                   |
| eveseat    | notifications  | 3.0.6                    |
| eveseat    | services       | 3.0.10                   |
| eveseat    | web            | 4.0.0-dev                |
| thirdparty | eve_online_sde | sde-20200330-TRANQUILITY |
```
Closes eveseat/seat#521 and eveseat/seat#524.

Add SDE UI indicator of version match, add SDE to versions report.

---

src/Http/Controllers/Auth/LoginController.php
src/Http/Controllers/Auth/SsoController.php
src/Http/Controllers/Configuration/SsoController.php
src/Http/Routes/Auth/Sso.php
src/Http/Routes/Configuration/Sso.php
src/Http/Validation/CustomSignin.php
src/Http/Validation/SsoScopes.php
src/resources/lang/en/seat.php
src/resources/views/auth/login.blade.php
src/resources/views/configuration/sso/view.blade.php

This PR adds support for defining multiple SSO scope profiles in the settings to allow different access levels depending on the type of user joining SeAT - for example different scope profiles for corporation, alliance and public.
Profiles are accessed using the route auth.eve.profile with the parameter of the profile name. Examples:
/auth/eve (for default profile, route via alias: `route('auth.eve')`)
/auth/eve/profile/alliance (for a profile named alliance, route via alias: `route('auth.eve.profile', 'alliance')`)
Default profile: 
Custom profile example: 
This may address and close eveseat/seat#382 - although the control over scopes stays with the SeAT administrator rather then the user, this allows extra flexibility that I think addresses the reason for requesting this capability.

enhance sso: ability to define scope profiles

---

src/Http/DataTables/Scopes/CharacterScope.php
src/Http/DataTables/Scopes/CorporationScope.php

PHP function strpos used for permissions checks had needle and haystack wrong way around so it was returning no permissions to be checked, resulting in only the users own characters being returned (unless a super user).

fix: datatables scopes for character and corporations

---

src/WebServiceProvider.php

Hello,
i propose to add production environment to horizon config.
currently, workers are not running with APP_ENV=production
thanks.

Adding production environment to horizon config

---

src/Http/Controllers/Support/SearchController.php
src/Http/DataTables/Scopes/CharacterMailScope.php

when user attempt to search a data, he receive error modals from assets, corporations, characters and skills table.
Closes eveseat/seat#635

fix(search): switch search engine to new ACL

---

src/database/migrations/2019_12_15_104132_create_squad_applications_table.php

MySQL does not support extended default value. As a result, previous migration version was not able to be executed on versions up to 8.0.21.

fix: remove default value on field message

---

src/Acl/Policies/SquadPolicy.php
src/Http/Controllers/Squads/SquadsController.php
src/Models/Squads/Squad.php
src/database/migrations/2020_08_23_103135_create_classified_field_on_squads_table.php
src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php
src/resources/views/squads/show.blade.php

Add the ability to hide a squad member list. A squad marked as classified will only show the member list for moderators and admins.
I got delayed so have the merge commit in here... Not sure if thats ideal or not...

feat: classified squads

---

src/Http/DataTables/Common/Intel/AbstractContactDataTable.php
src/Http/DataTables/Scopes/Filters/ContactCategoryScope.php

since we may not know exact contact identity, prefer using contact category rather than identity category in order to filter contacts results.

fix(ui): use contact table to determine category

---

src/resources/views/partials/alliance.blade.php
src/resources/views/partials/character.blade.php
src/resources/views/partials/corporation.blade.php

Remove entity name from cache and link only entity from which we own data.
Closes eveseat/seat#669

refactor: remove entity name from redis cache

---

src/Http/Controllers/HomeController.php
src/Traits/Stats.php

The getTotalSP method is only used on the homepage so I assume it is safe to refactor like this. 
Related to eveseat/seat#673

Refactor total SP stats to use all associated character IDs on homepage

---

src/resources/views/character/includes/summary.blade.php

Add a small check on the character summary header, next to user character counter.
The icon can have 3 states :
- valid, it's a green mark
- suspect, it's a warning exclamation point
- invalid, it's a red cross
Each state show a small tooltip while beeing hovered.
Closes eveseat/seat#694

fix(ui): add token check on character summary

---

src/Config/package.corporation.menu.php

a typo in the used permission requested to display "Custom Offices" entry was generating an invalid entry in security logs and prevent user other than admin to access this view even with proper permission.
Closes eveseat/seat#703

fix(acl): request proper permission while generating corporation menu

---

src/resources/views/squads/list.blade.php

a typo in the event in charge of refreshing squads cards was preventing search keywords to be forward when user attempt to change page.
Closes eveseat/seat#706

fix(squads): retrieve search keyword when changing page

---

src/Http/Controllers/Profile/ProfileController.php
src/resources/lang/en/seat.php
src/resources/views/error.blade.php
src/resources/views/profile/view.blade.php

instead showing an system exception, attempt to retrieve user account related to the newly selected main character.
if there is one, attempt to remove it. We can remove an account if he has no more keys attached to it. If the target character is still related to an account with keys, display a nice error message to assist end user.
Closes eveseat/seat#708

 fix: prevent exception when user change main character related to an existing account

---

src/Models/Filterable.php
src/database/migrations/2020_12_05_105939_upgrade_squads_maj4_min3_hf1.php
src/resources/views/components/filters/modals/filters/filters.blade.php
src/resources/views/components/filters/modals/filters/rule.blade.php
src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php

revamp the filter pattern to allow to pair rules by relation paths.
this allow to define a filter based on both skill name and skill level.
Closes eveseat/seat#693

feat(squads): add ability to restrict by skill level

---

src/Http/DataTables/Configuration/UsersDataTable.php

if stale data are cleared, or for any other reason, character sheet tied to a main character non longer exists, user in list is not properly displayed.
spawn a dummy character sheet using user metadata to ensure proper display.

fix(users): use user metadata instead main character relation in users list

---

src/Acl/Policies/AbstractPolicy.php
src/Acl/Policies/CharacterPolicy.php
src/Acl/Policies/CorporationPolicy.php
src/Acl/Policies/GlobalPolicy.php
src/Acl/Response.php
src/WebServiceProvider.php

log to security logs only if the user is asking for a page to which he does not have access to due to missing privileges.
currently, we're logging all acl events, including conditional display which is not expected.

fix(acl): log to security logs only on displayed page

---

src/Http/Controllers/Auth/SsoController.php

as per slack talk, it appears restore action does not use default field value, which make sense.

fix: force token version on authenticate

---

src/database/migrations/2021_01_17_150414_create_universe_moon_reports_table.php

MariaDB doesn't accept a foreign key constraint unless the columns on both sides are the same type, including if one side is an index. The moon_id column in universe_moon_contents is an index, so the moon_id column in universe_moon_reports must be as well in order to have a foreign key constraint between the two.
Ref: https://blog.mariadb.org/mariadb-innodb-foreign-key-constraint-errors/

fix: migration fails due to malformed foreign key constraint in MariaDB

---

src/Config/Permissions/global.php
src/Http/Controllers/Profile/ProfileController.php
src/Http/DataTables/Configuration/UsersDataTable.php
src/Models/User.php
src/resources/lang/en/permissions.php
src/resources/views/character/includes/summary.blade.php
src/resources/views/configuration/users/edit.blade.php
src/resources/views/profile/buttons/noscopes.blade.php
src/resources/views/profile/view.blade.php

Allows for granting the `Invalid Tokens` permission. This permission allows for linked characters with invalid tokens to still be displayed.
Caveats:
1. Linked characters with invalid tokens will not appear in the Users datatable baubles.
2. Viewing a character with no refresh token will not show the linked characters

feat: admin view invalid tokens

---

src/resources/lang/en/seat.php
src/resources/views/character/sheet.blade.php

Currently a char's remap dates are shown as today if the value is `null` this PR replaces today's date with `No Remap Found` in those cases.

fix: Replace today's date with a string when no remap exists.

---

src/Models/User.php
src/Observers/AbstractSquadObserver.php
src/Observers/SquadMemberObserver.php

when squads are sharing same roles and the user is non longer eligible from one of them but become eligible to the other - he was only getting part squads roles.
Closes eveseat/seat#754

fix(squads): prevent roles to be completely lost after new squad checks

---

src/Http/Controllers/Corporation/SummaryController.php
src/resources/lang/en/seat.php
src/resources/views/corporation/summary.blade.php

Implement a feature showing the number of active tokens on the corporation summary page. In order to be seen the user must have the `Corporation Tracking` permission.
Closes eveseat/seat#755

feat: Corp tracker

---

src/Observers/RefreshTokenObserver.php

when an user is using a character related to a revoked token - and that token is restored - we were not renewing squads checkup.

fix(squads): update user squads on token recovery

---

src/Observers/RefreshTokenObserver.php

when a token is updated and its scope not altered, squads check was not apply.
this control is revert to ensure squads membership is always up-to-date.
Closes eveseat/seat#770

fix(squads): refresh squads in all cases

---

src/Http/Controllers/Corporation/LedgerController.php

The ESS payout should also be considered as part of the player income generated by ratting.

fix: include ESS payout value in the bounty prize earnings

---

src/Models/User.php
src/database/migrations/2021_04_05_124225_fix_issue_eveseat_web_793.php

when user accounts are manually deleted, we were keeping attached tokens but soft deleting them.
as a result, if we had to recover the token or if the character was transferred - end user was not able to create a new account and get an exception due to user relation null exception.
since user deletion is an admin manual action, we assume token might be safely removed definitely.
however, we keep track of the action using security logs.
Closes eveseat/seat#793

fix(auth): when a user account is deleted, drop definitely attached tokens

---

src/Http/DataTables/Scopes/Filters/MoonRankScope.php

The current filter option worked lightly different from what users expect to see. Instead of filtering on a range of moons, it filtered only moons that has all the selected materials, instead of showing a compromised list that the user wanted.
For example, say you want to only see R16,R32 and R64 moons. With the previous setup, this was simply not possible since you would end up with a query like
->andWhere(moon is R16)->andWhere(moon is R32)->andWhere(moon is R64)
Altering the format of the query allows for all the same usecases at it previously provided, as well as support other usecases.

Implemented filtering based on current selection

---

src/resources/js/seat.js
src/resources/views/character/partials/delete.blade.php
src/resources/views/configuration/access/partials/action.blade.php
src/resources/views/configuration/users/buttons/delete.blade.php
src/resources/views/corporation/partials/delete.blade.php
src/resources/views/squads/buttons/application/reject.blade.php
src/resources/views/squads/buttons/roles/remove.blade.php
src/resources/views/squads/buttons/squads/kick.blade.php
src/resources/views/tools/moons/buttons/delete.blade.php

This PR adds a new `bootbox` confirmation dialog for deletion and uses the existing `confirmform` dialog so that (I hope?) all destructive operations have confirmation either in the form of `Are you sure you want to delete ${entity}` or in the form of `Are you sure you want to continue?`

Confirm destructive operations

---

src/resources/views/character/skills.blade.php
src/resources/views/home.blade.php

Corrects issue when using Jet skin, ticks have white backdrop enabled by default.

Fix backdrop for radar chart ticks

---

src/Http/Controllers/Corporation/ExtractionController.php
src/resources/lang/en/seat.php
src/resources/views/corporation/extraction/extraction.blade.php
src/resources/views/corporation/extraction/partials/card-body.blade.php
src/resources/views/corporation/extraction/partials/card.blade.php
src/resources/views/tools/moons/modals/components/components.blade.php
src/resources/views/tools/moons/modals/components/content.blade.php

This PR is focused on feedback given regarding some of the mining pages within SeAT. Changes listed below.
**Extractions**
- Multiple extractions for each structure are now able to be shown. This is important so that the active extraction is not overwritten when the moon drill is immediately restarted.
- Compact Nature - The default view for the extractions page now only shows the state of the pull, the location and the times. There is a toggle button at the top of the page which will expand the panel to also show the ores on the moon where present. 
- Moon Rate - The moon rate / percentage on this page has been replaced with the volume of ore expected for the extraction. Further to this there is a also a field for the total volume expected from the extraction.
- Icons - The icons have …

Mining Overhaul

---

src/Http/Controllers/HomeController.php
src/Traits/Stats.php
src/resources/lang/en/seat.php
src/resources/views/home.blade.php

Adding a new Home statistic for total ratted stat.
Attempts to solve https://github.com/eveseat/seat/issues/835
| Before  | This Code |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/171092/143540052-e39fabf2-1b5a-416f-87f2-89507f2d4e74.png) | ![image](https://user-images.githubusercontent.com/171092/143540083-24a97373-f2ef-43a1-b7d2-244ba7bc7ec1.png)  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/171092/143540135-90ef825c-4be6-4136-9d70-cbdba5a623e7.png) | ![image](https://user-images.githubusercontent.com/171092/143540169-15d3c083-7048-43f2-8433-80a1fc6e5b44.png) |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/171092/143540271-e5473001-bd47-46bb-b5f6-f01b9928affc.pn …

Total Ratted - Dashboard Summary Stat

---

src/resources/views/tools/moons/modals/components/content.blade.php

Together with eveseat/eveapi#320 this fixes the moon mining volumes in line with the updated 40k m3 base drilling volume.

fix: update moon chunk quantity

---

src/Http/DataTables/Scopes/AllianceScope.php
src/Http/DataTables/Scopes/CharacterMailScope.php
src/Http/DataTables/Scopes/CharacterNoteScope.php
src/Http/DataTables/Scopes/CharacterScope.php
src/Http/DataTables/Scopes/CorporationScope.php
src/Http/DataTables/Scopes/KillMailCharacterScope.php
src/Http/DataTables/Scopes/KillMailCorporationScope.php
src/Http/DataTables/Scopes/MiningCorporationScope.php

when resulting limitation list is excessively long, database driver is not handling data binding, resulting in an empty result

fix: avoid binding limitation sending raw IDs list

---

src/resources/views/character/includes/sidecard.blade.php
src/resources/views/character/sheet/employment-history.blade.php

- redesign corporation history, showing bigger row and improving scroll integration
- use ribbon in order to show token state rather than icon

feat: improve character sheet

---

src/resources/views/partials/character.blade.php
src/resources/views/partials/corporation.blade.php

Allows you to enter null into the character and corporation partials. My use case is writing something like this:
```
@include("web::partials.character",["character"=>$order->user->main_character ?? null])
```
This pr is intended to be deployed together with [https://github.com/eveseat/services/pull/157](https://github.com/eveseat/services/pull/157), but it will work even if the other pr is not merged, because we have null to int conversion in the `img()` function.

allow null in character and corporation partials

---

src/Traits/Stats.php

Currently only direct bounty, ESS and incursion payments are considered for ratted isk. 
Mission rewards should also be included.

Add mission rewards to total ratted isk on dashboard

---

composer.json

https://github.com/yajra/laravel-datatables had an[ issue](https://github.com/yajra/laravel-datatables/issues/2976) where some columns weren't rendered correctly. The issue is fixed in version 10.4, so we should start to use that version or newer

bump datatables version

---

src/Http/Validation/Custom/ArtisanCommand.php
src/Http/Validation/NewSchedule.php
src/WebServiceProvider.php

This pr allows you to add a command with argument to the seat command schedule.
fixes https://github.com/eveseat/seat/issues/867.

Allow command arguments in schedule

---

src/Config/web.skins.php
src/Http/Controllers/Profile/ProfileController.php
src/Http/Validation/ProfileSettings.php
src/WebServiceProvider.php

Makes skins a config that can be extended by plugins using `mergeConfigFrom`. Additionally it removes a reference to an old, no longer existing skin.

Make it possible to add more skins

---

.gitignore
src/Exceptions/InvalidFilterException.php
src/Models/Filterable.php
src/Models/QueryGroupBuilder.php
tests/Squads/AllianceRuleTest.php
tests/Squads/NoRulesTest.php

@Bluedagger on discord noticed that if a character is not in any alliance, and the squad contains a filter for `alliance is not x`, the user doesn't get added to the squad, even though he should.
While studying the `Filterable` trait code (https://github.com/eveseat/web/blob/c97b7cd1dd8cd5c063415ba0710d4b343dfdfef5/src/Models/Filterable.php), I noticed how messy and broken it was. I really struggled to first pin down the problem, and fixing it was even harder since it would have required to special case `is not` in multiple cases.
Therefore, I decided it's rewrite time! This allowed me to fix the original bug, and additionally:
- Make it more readable: There is no 8 levels deep nested code anymore
- Allow nesting of groups to arbitrary depths
- Add a new test case covering the bug
All …

Rewrite Filterable trait used for Squad filters

---

src/resources/views/character/includes/summary.blade.php

fixes https://github.com/eveseat/seat/issues/856
It is currently broken since character with expired tokens have their `refresh_token` soft-deleted. This means currently SeAT can't find the user from a character with expired token since `refresh_tokens` links characters to a user. The fix is to also consider deleted tokens when searching the user from a character.
The `global.invalid_tokens` permission is respected since it only affects `user->alts` and not the first part of the chain, `character->user`

Show alt characters in character summary when token has expired

---

src/WebServiceProvider.php

During the upgrade to laravel 10, we missed that the css framework of the pagination views changed away from bootstrap 4. This PR tells laravel to use bootstrap 4.

use bootstrap pagination templates

---

src/Http/Controllers/Corporation/LedgerController.php

As of https://github.com/eveseat/web/pull/643 character bounty payouts on the dashboard reflect bounties, incursion style payouts, and mission rewards.
This PR would bring the corporation bounty ledger inline with that readout.

Bring Corporation Wallet Ledger Bounty in line with Character Bounty Dashboard

---

.gitignore
composer.json
src/Exceptions/InvalidFilterException.php
src/Models/Filterable.php
src/Models/QueryGroupBuilder.php
src/Models/Squads/Squad.php
src/Observers/AbstractSquadObserver.php
src/database/migrations/2020_12_06_220254_upgrade_squads_maj4_min4_hf2.php
src/database/migrations/2024_02_11_155433_update_squad_filters.php
src/resources/views/squads/edit.blade.php
src/resources/views/squads/show.blade.php
tests/Squads/AllianceCorporationPairFiltersTest.php
tests/Squads/AllianceRuleTest.php
tests/Squads/CharacterRuleTest.php
tests/Squads/CorporationRuleTest.php
tests/Squads/ItemRuleTest.php
tests/Squads/NoRulesTest.php
tests/Squads/RoleRuleTest.php
tests/Squads/SameCharacterAcrossRulesTest.php
tests/Squads/SkillAffiliationRulesGroupsTest.php
tests/Squads/SkillLevelRuleTest.php
tests/Squads/SkillRuleTest.php
tests/Squads/SkillSkillLevelPairFiltersTest.php
tests/Squads/SsoScopeRuleTest.php
tests/Squads/TitleRuleTest.php

This PR redesigns how squad filters work to fix a few edge cases

Redesign squad filters

---

src/resources/views/character/sheet.blade.php

Some of my corp mates fail to load the character sheet because a type is missing from the DB. In that case, just display `unknown`

Fix null typeName

---

src/Models/Filterable.php
tests/Squads/SkillSkillLevelPairFiltersTest.php

force skill level relation to relate to skill selection

Squad other skill level

---

src/Models/Filterable.php

Crypta's fix didn't handle the case where you have groups and rules in the root group

ensure we don't confuse groups and rules

---

composer.json
src/Http/Controllers/Auth/SsoController.php

When a User clicks "Link Character" from the top-right menu, they should be prompted to use the same scopes as their Main Character.
The DB of refresh_tokens by user_id is not ordered naturally by created_at date, so the "first token" logic being replaced here pulls from a character other than Main Character, which means it will use potentially outdated defaults. Whereas the Main Character, being the one people actually use to Login with, is always prompted to use the newest default scopes that the SeAT Admin has chosen.
This fix allows SeAT Admins to change the default profile and provide an easy way for users with many characters linked to quickly updated all of the scopes across all characters.
- User has to log out of SeAT, log into SeAT with each and every character manually
- User …

V5 link character use main char scopes

---

src/Http/Controllers/Character/SheetController.php
src/resources/views/character/sheet.blade.php

small QoL change to see which of your jumpclones have implants
Could use a mouseover to show the name of a given implant, but I could not find how to map the ID to text

add implant icons

---

src/Config/web.characterfilter.php
src/Events/CharacterFilterDataUpdate.php
src/Http/Composers/CharacterFilter.php
src/Http/Controllers/Configuration/ScheduleController.php
src/Http/Routes/Configuration/Schedule.php
src/Listeners/CharacterFilterDataUpdatedSquads.php
src/Listeners/CharacterFilterDataUpdatedTokens.php
src/Models/CharacterSchedulingRule.php
src/Observers/AbstractCharacterFilterObserver.php
src/Observers/CharacterAffiliationObserver.php
src/Observers/CharacterAssetObserver.php
src/Observers/CharacterRoleObserver.php
src/Observers/CharacterSkillObserver.php
src/Observers/CharacterTitleObserver.php
src/Observers/RefreshTokenObserver.php
src/WebServiceProvider.php
src/database/migrations/2024_08_15_create_character_scheduling_rules_table.php
src/resources/lang/en/seat.php
src/resources/views/components/filters/buttons/filters.blade.php
src/resources/views/configuration/schedule/view.blade.php
src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php
tests/Acl/AlliancePolicyTest.php
tests/Acl/CharacterPolicyTest.php
tests/Acl/CorporationPolicyTest.php

This PR is the web side of bringing per-character esi update intervals to seat. It builds upon https://github.com/eveseat/eveapi/pull/409 and adds a user interface+automation using squad filter for it.
How it works: Admins can specify "character scheduling rules". They are a squad-style character filter and an associated update interval. For every character, seat checks if they are eligible for a scheduling rule by checking the filter of that rule. From all rules that apply to a character, the rule with the shortest update interval is used. If no rule applies, the old default of 1 hour applies.
Internal changes: This PR refactors the observer side of squads so that the observers can also be used for other kinds of filters, like the character scheduling rules. The available filter rules …

Granular esi scheduling for characters

---

src/Http/Controllers/Configuration/ScheduleController.php
src/Models/CharacterSchedulingRule.php

Some reported me that they get a error 500 when updating rules just after upgrading. This is the same bug that crypta discovered. It turns out I missed a line while copy&pasting the original fix.
Error:
```
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'last_update' doesn't have a default value at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:45)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php(45): PDOStatement->execute()
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\MySqlConnection->Illuminate\\Database\\{closure}('insert into `re...', Array)
#2 …
```

fix: allow updating character scheduling rules for new tokens

---

src/Jobs/UpdateCharacterFilters.php

Installs with many squads (50+) run out of ram when attempting to run `seat:filters:update`. By having fewer characters in RAM at a time, this should no longer happen. 
Going from 200 to 5 characters at a time might seem a bit drastic, but experimentally a user had to increase the memory limit about 10x to make it pass. Additionally, we want some margin of safety.

Prevent squad update from running out of memory with many squads

---

src/resources/js/seat.js

Using .submit() to submit a form from javascript doesn't trigger the form's `submit` event. `submit` is commonly used for form validation or injecting data from javascript. Instead of `submit`, we can use `requestSubmit`
See also: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit#usage_notes

fix: trigger normal form events when using .confirm[delete][form]

---

src/resources/views/auth/login.blade.php

Adding the login-logo back to the seat logo on the login page to allow for css modification.

fix: add styling back to logo

---

src/Http/Controllers/Configuration/SeatController.php

When the admin contact email is updated, workers will not pick up this change without a restart. This PR adds a warning that SeAT must be restarted.

feat: contact email change restart warning

---

src/database/migrations/2025_02_11_000000_remove_deprecated_sso_scopes_profiles.php

Fixes the following migration issue reported by `@nunu` on discord:
```
front-1      |    INFO  Running migrations.
front-1      | 
front-1      |   2025_02_11_000000_remove_deprecated_sso_scopes_profiles ........... 1ms FAIL
front-1      | 
front-1      | In 2025_02_11_000000_remove_deprecated_sso_scopes_profiles.php line 44:
front-1      |
front-1      |   Attempt to read property "value" on null
front-1      |
front-1      | 
```
This happens if not sso scope profile has been set up.

fix: sso scope profile migration without any profile

---

tests/Acl/CorporationPolicyTest.php

As it stands right now, the CorporationInfo factory might generate `99000000` as alliance id with a 10% probability, but the test case assumes this never happens.
This is just one of the random testing failures. I'm sure there are more, but it is easier to track them down when they happen instead of proactively.

fix one broken unit test

---

src/resources/views/profile/view.blade.php

I've been playing around with some custom seat skins. This one button directly next to the skin selector has been really ugly because it overrides some button styles. With the default and jet skin, it looks basically unchanged, but with any other skins, this button now automatically looks good.

use bootstrap classes instead of style attribute for button

---

src/Http/Controllers/Profile/ProfileController.php
src/resources/lang/de/seat.php
src/resources/lang/en/seat.php
src/resources/views/profile/modals/scopes/content.blade.php

With this PR, in addition to the scopes granted on a token, we also show the linked scope profile. This is relevant to e.g. debug issues when a scope profile gets deleted, but there are still tokens linked to it or when assessing the effect of changing a token profile.

feature: display scope profile in scopes view

---

src/resources/views/character/skills.blade.php

I've been getting some 500s because the new Advanced Armor Layering skill is not yet in the SDE. 
Instead of giving a 500 for characters with this skill, this PR will just ignore the skill.

fix: don't show skill if we don't know its name
