src/resources/views/character/includes/summary.blade.php
src/resources/views/corporation/includes/summary.blade.php

Just a few lines, reused existing translation

add updated_at timestamps to Character and Corporation Sheet summary

---

src/lang/fr/seat.php

Adding five new translation :
- Channels
- Channel members
- Motd
- Bookmark
- Coordinates
- Folder
- Created By

Translate SeAT in french according to 1.0.11

---

src/resources/views/character/mail-read.blade.php
src/resources/views/character/mail-timeline.blade.php

Fix the issue about unkown-item in mail timeline and read-mail
Ticket https://github.com/eveseat/seat/issues/9

fix issue #9

---

src/resources/views/character/contacts.blade.php
src/resources/views/corporation/contacts.blade.php

I'm sorry, i miss the neutral and negative display.
Added for corporation aswell
https://github.com/eveseat/seat/issues/5

fix issue #5 about labels display on neutral and negative standing

---

src/resources/views/corporation/starbase/status-tab.blade.php
src/resources/views/corporation/starbase/summary.blade.php

- Update calc formula
- Adding ceil in order to get round item unit (ccp like)
Fix issue https://github.com/eveseat/seat/issues/43

Fix issue eveseat/seat issues#43

---

src/resources/views/includes/header.blade.php

This commit fix the wishlist #38 started here https://github.com/eveseat/seat/issues/38

Fix issue eveseat/issues#38

---

src/resources/views/corporation/starbase/status-tab.blade.php
src/resources/views/corporation/starbase/summary.blade.php

update state color for offline/anchor state
https://github.com/eveseat/seat/issues/89

fix reinforcement time using API stateTimeStamp

---

src/resources/views/corporation/ledger/bountyprizesbymonth.blade.php
src/resources/views/corporation/ledger/planetaryinteraction.blade.php
src/resources/views/corporation/ledger/walletsummary.blade.php

Generate the total value of monthly Bounty Prize and PI ledger within the view as a panel-footer.

Added total values to the Bounty Prizes and PI monthly ledgers.

---

src/lang/en/seat.php

L283, changed "manuall" to "manually"

Adjusted a typo when doing mass import of API

---

src/resources/views/character/contacts.blade.php
src/resources/views/corporation/contacts.blade.php

Filtering link based on contact type (2 = corp, 16159 = alliance, other should be player)
cf. invTypes table

Add contact tracking links into character and corporation contact list

---

src/Http/Controllers/Character/ViewController.php
src/lang/en/seat.php
src/lang/fr/seat.php
src/resources/views/character/sheet.blade.php

Required PR from services repository about character corporation title

Add corporation titles to character sheet with color parsing

---

src/Config/web.config.php

Update full api mask

---

src/Http/Controllers/Api/KeyController.php
src/resources/views/api/detail.blade.php

Add paid-until in Key Details view 

---

src/Http/Controllers/Configuration/SeatController.php
src/Validation/SeatSettings.php
src/lang/en/seat.php
src/resources/views/api/add.blade.php
src/resources/views/api/ajax/result.blade.php
src/resources/views/configuration/settings/view.blade.php

Renaming the old minimum required mask as "min_character_access_mask"
Answer to wish eveseat/seat#129

Create a new minimum required mask dedicated for corporation

---

src/lang/en/seat.php
src/resources/views/character/contracts.blade.php
src/resources/views/corporation/contracts.blade.php

Answer to wish eveseat/seat#68

Add collateral amount into contract list

---

src/resources/views/character/list.blade.php

add alliance icon and name into character list according to wish https://github.com/eveseat/seat/issues/134

add alliance icon and name into character list

---

composer.json
src/Http/Controllers/Configuration/SeatController.php
src/Http/Routes/Configuration/Seat.php
src/lang/en/seat.php
src/resources/views/configuration/settings/view.blade.php
src/resources/views/includes/footer.blade.php

Depends on https://github.com/eveseat/console/commit/5c7f85b8244d76e9cf957476119e9ba0747027c6

add SDE version into both footer and settings page

---

src/resources/views/api/detail.blade.php

fix paid-until issue in detail api key view due to possible missing status

fix paid-until issue in detail api key view

---

src/Config/package.character.menu.php
src/Config/package.corporation.menu.php
src/Config/package.sidebar.php
src/Http/Composers/AbstractMenu.php
src/Http/Composers/CharacterMenu.php
src/Http/Composers/CorporationMenu.php
src/Http/Composers/Sidebar.php
src/WebServiceProvider.php
src/resources/views/character/includes/menu.blade.php
src/resources/views/corporation/includes/menu.blade.php
src/resources/views/includes/sidebar.blade.php

Refactoring a bit menu composer in order to define a menu composer type and use config file instead hard coded entry

Refactoring a bit menu composer

---

src/resources/views/auth/login.blade.php

Currently we just redirect to form and display disabled registration message.
This commit show only registration link if registration are enabled.

Hide registration link if registration is disabled

---

src/Http/Controllers/HomeController.php
src/Http/Routes/Home.php
src/lang/en/seat.php
src/resources/views/home.blade.php

show skill charts on dashboard for selected main character
depends on https://github.com/eveseat/services/pull/10

add skills related chart

---

src/Http/Controllers/Auth/SsoController.php
src/Http/Routes/Auth/Sso.php
src/lang/en/seat.php
src/resources/views/auth/ssoconfirmation.blade.php
src/resources/views/profile/view.blade.php

fix multiple user creation when user is already owning an account and authenticate with SSO
add the ability for existing user to authenticate through SSO from their profile
add the ability to alter existing user with SSO credentials after credentials confirmation

Fix SSO authentication

---

src/Http/Controllers/Api/KeyController.php
src/Http/Routes/Api/Key.php
src/lang/en/seat.php
src/resources/views/api/detail.blade.php
src/resources/views/api/list.blade.php

Add a button on key detail and key list which enable to disable key(s).

add disable key function

---

src/Http/Controllers/Api/KeyController.php
src/resources/views/search/components/apikey.blade.php
src/resources/views/search/result.blade.php

add the ability to search on keyID field from ApiKey
add key filtering into the global search feature

improve search feature on api key

---

src/Http/Controllers/Api/KeyController.php
src/Http/Controllers/Support/SearchController.php
src/Http/Routes/Support/Search.php
src/resources/views/search/components/apikey.blade.php

depends on https://github.com/eveseat/services/pull/12

Key list search

---

src/Acl/AccessChecker.php

fix issue related to permission when an object owner get all permission, including system permission.

fix issue related to permission

---

src/Acl/AccessChecker.php

move wildcard check logic to "hasAffiliationAndPermission"

update permission system in order to have a faster discover

---

src/Http/Composers/AbstractMenu.php
src/Http/Composers/CharacterMenu.php
src/Http/Composers/CorporationMenu.php

Provide permission affiliation setting into menu composer in order to fix issue when an user go on character or corporation view.

Fix ACL issue on menu display

---

src/Http/Controllers/Configuration/ScheduleController.php

Example: from */5 * * * * *  to */5 * * * *

Modified cron statements to proper format. Changed from 6 positions to 5

---

src/resources/views/includes/header.blade.php

fix acl minor issue related to job dashboard access from header buttons

---

src/resources/views/api/list.blade.php
src/resources/views/character/contracts.blade.php
src/resources/views/character/industry.blade.php
src/resources/views/character/intel/notes.blade.php
src/resources/views/character/intel/standingscompare.blade.php
src/resources/views/character/intel/summary.blade.php
src/resources/views/character/journal/journal.blade.php
src/resources/views/character/killmails.blade.php
src/resources/views/character/list.blade.php
src/resources/views/character/mail.blade.php
src/resources/views/character/market.blade.php
src/resources/views/character/transactions.blade.php
src/resources/views/configuration/security/logs.blade.php
src/resources/views/corporation/contracts.blade.php
src/resources/views/corporation/industry.blade.php
src/resources/views/corporation/journal.blade.php
src/resources/views/corporation/killmails.blade.php
src/resources/views/corporation/list.blade.php
src/resources/views/corporation/market.blade.php
src/resources/views/corporation/transactions.blade.php
src/resources/views/search/components/apikey.blade.php
src/resources/views/search/components/character.blade.php
src/resources/views/search/components/characterassets.blade.php
src/resources/views/search/components/corporation.blade.php
src/resources/views/search/components/mail.blade.php
src/resources/views/search/components/skills.blade.php

improve tables usability by adding paginate on both header and footer as well as filter feature

improve tables usability by adding paginate on both header and footer

---

src/Http/Controllers/Configuration/SeatController.php
src/resources/views/configuration/settings/view.blade.php

pugx service is dead, replace all badge by shields.io
update SDE badge to flat design
fix SDE badge label to use `-` (dash) instead `.` (dot)

pugx service is dead, replace all badge by shields.io

---

src/resources/views/character/industry.blade.php
src/resources/views/corporation/industry.blade.php

This improve industry view by adding filter toolbar and replace startDate by endDate
Request eveseat/seat#184
Depends on eveseat/eveapi#21

add status filters on industry tables for both character and corporation

---

src/resources/views/character/industry.blade.php
src/resources/views/corporation/industry.blade.php

fix merge issue due to conflicting dom property between indie filter PR and paginate duplication PR

fix merge issue

---

src/Http/Controllers/Character/ContractsController.php
src/resources/views/character/contractitems.blade.php
src/resources/views/character/contracts.blade.php
src/resources/views/partials/contractcontentsbutton.blade.php
src/resources/views/partials/contractissuer.blade.php
src/resources/views/partials/contracttype.blade.php

provide a missing commit related to character contract

Character 3.x

---

src/Http/Controllers/Profile/ProfileController.php
src/database/migrations/2018_04_07_130814_drop_unique_email.php
src/resources/views/profile/view.blade.php

cascading email update over all linked account

---

src/Http/Controllers/Character/SheetController.php

fix employment history sort

---

src/resources/views/character/assets.blade.php

* Show Ship-/Containername + TypeName in parenthesis
* Show only TypeName for mods/ammo etc.

Align assets representation to ingame experience

---

src/Events/Register.php
src/Http/Controllers/Auth/SsoController.php
src/WebServiceProvider.php
src/resources/views/character/assets.blade.php

* a registered event is being fired when a new user is created
* upon that event an 'esi:update:character' with the character_id
of the user is being triggerd
PR depends on eveseat/console#12

 Pull data for newly created users

---

src/resources/views/character/includes/summary.blade.php

allow route bridging between linked characters

---

src/Acl/AccessChecker.php

improve vanilla ACL in order to allow corporation affiliation on character permission

improve vanilla ACL in order to allow corporation affiliation on char

---

src/Http/Controllers/Tools/StandingsController.php
src/Http/Validation/StandingsExistingElementAdd.php
src/resources/views/tools/standings/edit.blade.php

upgrade standing builder to ESI

---

src/Http/Controllers/Character/IntelController.php
src/resources/views/character/intel/includes/menu.blade.php
src/resources/views/character/intel/partials/alliancename.blade.php
src/resources/views/character/intel/partials/charactername.blade.php
src/resources/views/character/intel/partials/corporationname.blade.php
src/resources/views/character/intel/summary.blade.php
src/resources/views/character/sheet.blade.php

depends on
eveseat/services#44
eveseat/console#15
eveseat/eveapi#67

update intel layouts for ESI

---

src/Acl/AccessChecker.php

only grant access to a corporation with wildcard permission if corporation match !

fix ACL issue on corporation level

---

src/Http/Controllers/Corporation/ContactsController.php
src/resources/views/character/contacts.blade.php
src/resources/views/corporation/contacts.blade.php

depends on eveseat/eveapi#68
depends on eveseat/services#45

upgrade corporation contact in order to implement labels

---

src/Models/User.php
src/resources/views/configuration/users/edit.blade.php
src/resources/views/configuration/users/list.blade.php
src/resources/views/profile/view.blade.php

depends on eveseat/services#51

fix route and user/group relationships on user layouts

---

src/resources/views/character/sheet.blade.php

fix skill queue refresh according to finished date instead position

---

src/resources/views/configuration/settings/view.blade.php

fix doc link to the new amazing documentation ♥

---

src/resources/views/character/includes/summary.blade.php
src/resources/views/character/sheet.blade.php

this apply on character sheet layout

filtering displayed skills and wallet information according to perms

---

src/resources/views/character/includes/summary.blade.php

This will fix the issue eveseat/seat#309
The characters ship will get displayed properly including type and name.
* **Pull request**: eveseat/eveapi#93
* **Issue**: eveseat/seat#309

fix: The characters ship will now get displayed properly.

---

src/resources/assets/img/favico/manifest.json

updated app name and added missing fields needed for web app manifests

updated missing fields in web app manifest

---

src/Models/Group.php

related to main character and email according to web#b13 modification

provide extra helper attribute to Group

---

src/Http/Validation/ProfileSettings.php
src/resources/views/includes/header.blade.php
src/resources/views/includes/sidebar.blade.php
src/resources/views/profile/view.blade.php

admin user have to stay a special user

remove ability to bind admin user to EVE

---

src/Models/Group.php

* Returning Main Character not User of Group

Return MainCharacter of Group

---

src/resources/views/corporation/starbase/status-tab.blade.php
src/resources/views/corporation/starbase/summary.blade.php

fix starbase layout (progress and offline timer)

---

src/resources/views/character/sheet.blade.php

in order to close eveseat/seat#295

fix skill training human conversion

---

src/resources/views/character/contacts.blade.php
src/resources/views/corporation/contacts.blade.php
src/resources/views/includes/javascript/id-to-name.blade.php

also drop eve-hunt and eve-kill from corp contacts since platform are deprecated

improve id to name resolver in order to support resolving in link

---

src/resources/views/character/mining-ledger.blade.php

This PR resolves https://github.com/eveseat/seat/issues/381

respect number format from user settings

---

src/Http/Controllers/HomeController.php
src/lang/en/seat.php
src/resources/views/home.blade.php

Add overview box with total mined isk

---

src/Models/Group.php
src/Models/User.php
src/WebServiceProvider.php

Dependencies :
- eveseat/api#21 : contains endpoint annotations and some fixes related to core and ACL pre-release modifications
- eveseat/eveapi#108 : contains models annotations and some fixes related to cast
Improvements :
- Provide extended documentation for swagger support
- Use multiple directories annotations source for swagger documentation generator
.

Improve api docs

---

src/lang/en/seat.php
src/resources/views/character/industry.blade.php
src/resources/views/corporation/industry.blade.php

Add a end column to both character and corporation industry jobs
Closes eveseat/seat#392

feat(industry jobs): Add end column to industry jobs table

---

src/resources/views/partials/industrysystem.blade.php

Update queries from both character and corporation industry services
to use universe_structure table in order to resolve citadels name

fix(industry jobs): Fix location field

---

src/resources/views/profile/view.blade.php

* Added token status to linked characters.
* Added tooltips to status

Add token status linked characters

---

src/Http/Controllers/Character/CharacterController.php
src/Http/Routes/Character/View.php
src/resources/views/character/list.blade.php
src/resources/views/character/partials/alliancename.blade.php
src/resources/views/character/partials/charactername.blade.php
src/resources/views/character/partials/corporationname.blade.php

* This regards  feature request https://github.com/eveseat/seat/issues/359
* with SeAT Group Tab one can receive another table with only
character belonging to the users group.

Add tab for users with `character.list` permission

---

src/resources/views/corporation/ledger/bountyprizesbymonth.blade.php
src/resources/views/corporation/tracking.blade.php

fix(corporation): Fix number sort on bounty ledger

---

src/Http/Controllers/Character/CharacterController.php

* Making use of ´getAllCharactersInGroup()´ method.
* Depends on https://github.com/eveseat/services/pull/62
This will result in completing https://github.com/eveseat/seat/issues/359 and fixing error report from: https://github.com/eveseat/web/pull/207#issuecomment-414624274

Show all Characters in SeAT-Group only tab

---

src/resources/views/includes/right_sidebar.blade.php
src/resources/views/layouts/app.blade.php

Added section for right-sidebar as per the AdminLTE examples

section for right-sidebar added

---

src/Models/Group.php

* resolves https://github.com/eveseat/seat/issues/431
* depends on: https://github.com/eveseat/api/pull/26
This is just the documentation update:

Add main_character_id to group-list

---

src/Http/Controllers/Character/CharacterController.php

No more datatable-error when using admin-user

Accept admin user

---

src/Http/Controllers/Character/KillmailController.php

This solves: https://github.com/eveseat/seat/issues/484

change `is_nan` to `is_null`

---

src/Http/Controllers/Character/KillmailController.php
src/resources/assets/js/seat.js

Precision fix

---

src/resources/views/configuration/users/list.blade.php

This PR fulfills two puroseses:
1) delay searching 
2) resolves: https://github.com/eveseat/seat/issues/490 
the main reason is the search delay. Larger seat instances take a long time to query every keyup.

Delay search to query less

---

src/Acl/AccessChecker.php

This resolves: https://github.com/eveseat/seat/issues/442

442 inverse character permission on yourself denys access to own data

---

src/Http/Controllers/Character/ContractsController.php
src/resources/views/character/contracts.blade.php
src/resources/views/partials/contractcontentsbutton.blade.php

fix https://github.com/eveseat/seat/issues/499 
* generate url for contract-details in the controller

449 fix contract details for linked characters

---

src/Http/Controllers/Corporation/TrackingController.php
src/Http/Routes/Corporation/View.php
src/resources/views/corporation/partials/location.blade.php
src/resources/views/corporation/partials/refresh-token.blade.php
src/resources/views/corporation/tracking.blade.php

Fix corporation tracking and move to server side datatables. 
requires: https://github.com/eveseat/services/pull/78
resolves: https://github.com/eveseat/seat/issues/488 and https://github.com/eveseat/seat/issues/308

Corporation tracking

---

src/Http/Controllers/Corporation/KillmailsController.php
src/resources/views/corporation/killmails.blade.php

requires: https://github.com/eveseat/services/pull/81/files 
Testing and closing: https://github.com/eveseat/seat/issues/456

Some refactoring in the service and view to be consistent with character view

---

src/Http/Controllers/Corporation/WalletController.php
src/resources/views/corporation/wallet/journal/journal.blade.php

* Show 1 tab per division
* refactor service trait
Testing and closing: https://github.com/eveseat/seat/issues/454
requires: https://github.com/eveseat/services/pull/82

Refactor corporation journal to work as in game.

---

src/Http/Controllers/Corporation/MarketController.php
src/resources/views/corporation/market.blade.php

* Test and close https://github.com/eveseat/seat/issues/455
* Add Issued_by column to view
requires: https://github.com/eveseat/services/pull/83

Refactor Corporation Market

---

src/resources/assets/css/seat.css
src/resources/assets/js/seat.js
src/resources/views/includes/header.blade.php

In order to make the user drop-down more identifiable, provide a caret
near to it.
Closes eveseat/seat#496

feat(header): Add a caret near profile user drop-down

---

src/Http/Controllers/Configuration/UserController.php
src/resources/views/configuration/users/list.blade.php

Add ability to filter users list

Add ability to filter users for valid or invalid refresh_tokens.

---

src/resources/views/corporation/killmails.blade.php

does what the title says fix https://github.com/eveseat/seat/issues/509

Fix corp killmails table header missarrangement

---

src/Http/Controllers/Character/ContactsController.php
src/Http/Controllers/Support/SearchController.php

should have used `entity_id` not `id`

Used wrong attribute for filterColumn

---

src/resources/views/configuration/settings/view.blade.php

Adding loading spinner to changelog

Add loading spinner to changelog

---

src/Http/Controllers/Corporation/LedgerController.php

fix(corporation): Fix Planetary Interaction Ledger

---

src/lang/cn/seat.php

fix translations do not make any sense.

update Chinese translation

---

src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Support/FastLookup.php
src/Http/routes.php
src/resources/views/configuration/access/edit.blade.php
src/resources/views/tools/standings/edit.blade.php

1. Implemented `FastLookup`, which can be used as autocompletion datasource. API is [Select2 Ajax Compatible](https://select2.org/data-sources/ajax)
2. Replace inline options with Select2 Ajax Datasource on Role Edit page. This fixed eveseat/seat#556

implement FastLookup

---

src/Http/Controllers/Auth/LoginController.php
src/Http/Controllers/Configuration/SeatController.php
src/resources/views/configuration/sso/view.blade.php

parameters from .env is only read at boot stage - then, configuration
files are used.
https://github.com/laravel/framework/issues/21727

fix(config): put environment variables into config file

---

src/Config/package.sidebar.php
src/Http/Controllers/Configuration/SeatController.php
src/Http/Routes/Configuration/Seat.php
src/lang/en/seat.php
src/resources/views/about.blade.php

according to section 7.1 of the license agreement, we had to specify the
following mention.
https://developers.eveonline.com/resource/license-agreement
render this way :

feat(license): add CCP copyright in footer

---

src/Http/Controllers/Corporation/ExtractionController.php

fix(extractions): ensure integrity of moon content

---

src/Http/Controllers/Character/SheetController.php

**DEPENDENCIES** : eveseat/eveapi#164

refactor(titles): use relationship instead atomic table

---

src/Http/Controllers/Character/IndustryController.php
src/Http/Controllers/Corporation/IndustryController.php
src/Http/DataTables/Character/Industrial/IndustryDataTable.php
src/Http/DataTables/Common/Industrial/AbstractIndustryDataTable.php
src/Http/DataTables/Corporation/Industrial/IndustryDataTable.php
src/Http/DataTables/Scopes/Filters/IndustryActivityScope.php
src/Http/DataTables/Scopes/Filters/IndustryStatusScope.php
src/resources/views/character/industry.blade.php
src/resources/views/corporation/industry.blade.php

- restore industry jobs status filters
- add industry jobs activity filters
- improve rendered tables

feat(industry): improve filterability of industry tables

---

src/Http/Controllers/Character/SkillsController.php
src/Http/Routes/Character/View.php
src/resources/views/character/skills.blade.php

feat(skills): add a button to export skills with Pyfa format

---

src/resources/views/character/includes/summary.blade.php

feat(character): add number of toons on character summary

---

src/Http/DataTables/Character/CharacterDataTable.php
src/Http/DataTables/Corporation/CorporationDataTable.php

feat(list): sort characters and corporation in ascending order

---

src/Http/Controllers/Corporation/StructureController.php
src/Http/Routes/Corporation/View.php
src/resources/views/common/fittings/buttons/detail.blade.php
src/resources/views/common/fittings/buttons/export.blade.php
src/resources/views/common/fittings/buttons/insurance.blade.php
src/resources/views/common/fittings/modals/fitting/content.blade.php
src/resources/views/common/fittings/modals/fitting/slots.blade.php
src/resources/views/corporation/structures/buttons/detail.blade.php
src/resources/views/corporation/structures/buttons/export.blade.php
src/resources/views/corporation/structures/list.blade.php
src/resources/views/corporation/structures/modals/fitting/content.blade.php
src/resources/views/corporation/structures/modals/fitting/fitting.blade.php
src/resources/views/corporation/structures/modals/fitting/slots.blade.php

feat(structures): add fittings modal and export button

---

src/Acl/AccessChecker.php
src/Acl/AccessManager.php
src/Config/Permissions/global.php
src/Config/package.sidebar.php
src/Http/Controllers/Configuration/AccessController.php
src/Http/Controllers/Configuration/UserController.php
src/Http/DataTables/Common/Intel/AbstractContactDataTable.php
src/Http/Routes/Character/View.php
src/Http/Routes/Support/FastLookup.php
src/Http/Routes/Support/List.php
src/Http/Routes/Tools/Standings.php
src/Http/routes.php
src/Models/Acl/Role.php
src/Models/User.php
src/database/migrations/2019_10_24_113450_drop_affiliations_table.php
src/database/migrations/2019_10_24_113552_drop_affiliation_role_table.php
src/database/migrations/2019_10_24_113617_drop_affiliation_user_table.php
src/resources/lang/en/permissions.php
src/resources/views/character/partials/delete.blade.php
src/resources/views/configuration/access/list.blade.php
src/resources/views/configuration/access/partials/permissions.blade.php
src/resources/views/configuration/users/edit.blade.php
src/resources/views/corporation/partials/delete.blade.php
src/resources/views/partials/standing.blade.php
src/resources/views/tools/standings/edit.blade.php

feat(acl): restrict standing builder access

---

src/Http/Controllers/Corporation/MarketController.php

fix(orders): address a typo on the corporation market table

---

src/Acl/AccessChecker.php

fix(acl): remove corp journal and corp transactions from Jun. Accountant

---

src/Http/DataTables/Character/CharacterDataTable.php

fix(characters): Add affiliation to data name to match query so that we don't get a query error

---

src/Http/Controllers/Support/SearchController.php
src/Http/DataTables/Character/CharacterDataTable.php
src/Http/DataTables/Corporation/CorporationDataTable.php
src/resources/lang/en/seat.php
src/resources/views/search/components/character.blade.php
src/resources/views/search/components/character_assets.blade.php
src/resources/views/search/components/skills.blade.php

This fixes the various DataTables errors on the search page, mostly due to the need to update our corporation and alliance relation to be through the affiliation model from recent changes. Also adding a missing language string for faction to the English language file.

fix(search): Fixes to DataTables errors on Search page

---

src/Http/Controllers/Corporation/LedgerController.php

year and month are set as nullable types, but they still have to have a value passed or a default.

fix(ledger): too few arguments passed to controller functions

---

src/Http/Controllers/Corporation/TrackingController.php
src/resources/views/corporation/partials/location.blade.php
src/resources/views/corporation/tracking.blade.php

Related to https://github.com/eveseat/eveapi/pull/197 and https://github.com/eveseat/services/pull/120.
- Add column to DataTables for ship type.
- Remove ship type from locations partial view.
- Used UniverseNames to load the character name so sorting worked correctly.
- Added the users main character as a hidden column and set DataTables to sort the character name column by the main character.

Corp member tracking using updated model relations, refactored to fix sorting and add ship column

---

src/resources/views/squads/buttons/application/approve.blade.php
src/resources/views/squads/buttons/application/reject.blade.php
src/resources/views/squads/buttons/application/show.blade.php

Squads button view typo fix

---

src/Http/Controllers/Squads/ApplicationsController.php

Add validation to ensure message set

Add validation to ensure message set

---

src/Config/Permissions/global.php
src/Config/Permissions/moon.php
src/Config/package.sidebar.php
src/Http/DataTables/Tools/MoonsDataTable.php
src/WebServiceProvider.php
src/resources/lang/en/permissions.php
src/resources/views/corporation/extraction/partials/card.blade.php
src/resources/views/tools/moons/list.blade.php

Three new Moon Reporter permissions:  
- create_moon_reports
- view_moon_reports
- manage_moon_reports
Changed all references to old permissions to the appropriate(?) new permissions.

Permission changes

---

src/Http/Composers/CharacterLayout.php
src/Http/Controllers/Character/AssetsController.php
src/Http/DataTables/Squads/CandidatesDataTable.php
src/Http/DataTables/Squads/MembersDataTable.php
src/resources/css/seat.css
src/resources/css/skins/jet.css
src/resources/views/character/assets.blade.php
src/resources/views/character/includes/summary.blade.php
src/resources/views/character/partials/asset-type.blade.php
src/resources/views/layouts/app.blade.php
src/resources/views/profile/view.blade.php
src/resources/views/squads/show.blade.php

This PR is fixing some minor issue on user profile which avoid "current format" in number section to be properly displayed (user settings were not used).
It also include a rounding precision on character security status displayed on summary sidebar up to two digits and avoid a null exception due to missing token.
Last but not least, it introduce a new skin which enable Dark Mode. That skin, called Jet, is based on Gruvbox colors (https://github.com/morhetz/gruvbox). Maybe further will follow later.
Depends on eveseat/services#123

Small UI fix and a first dark-style skin

---

src/Http/Controllers/Configuration/SeatController.php
src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Support/FastLookup.php
src/Http/Validation/SeatSettings.php
src/database/migrations/2019_11_12_220840_drop_groups_table.php
src/resources/lang/en/settings.php
src/resources/views/configuration/settings/view.blade.php

The user update migration is now fully working, including admin user and ID generation.
Together with that fix, this pull request is also providing some UI change on settings view to allow user to select the region from which he wants receive prices updates.

Migration fix and UI modification related to new prices management

---

src/Config/web.config.php
src/Http/DataTables/Common/AbstractColumn.php
src/Http/DataTables/Common/Intel/AbstractAssetDataTable.php
src/Http/DataTables/Corporation/Columns/AssetLocationFlagColumn.php
src/Http/DataTables/Corporation/Columns/AssetStationColumn.php
src/Http/DataTables/Corporation/Intel/AssetDataTable.php

use dedicated column handler for station/structure and location in order to make table usable for both characters and corporations.
also allow division to be searchable by display name.

refactor(assets): increase abstraction on datatable

---

src/Http/DataTables/Common/Industrial/AbstractIndustryDataTable.php
src/resources/views/character/industry.blade.php
src/resources/views/common/industries/partials/progress.blade.php
src/resources/views/corporation/industry.blade.php

This addresses the UI enhancement request in and closes eveseat/seat#398.

UI enhancement: add progress bar to industry jobs

---

src/Http/Controllers/Auth/SsoController.php

refactor(auth): ensure user can authenticate if there are no SSO issue

---

src/Http/Controllers/Tools/MoonsController.php
src/Http/DataTables/Scopes/Filters/ConstellationScope.php
src/Http/DataTables/Scopes/Filters/MoonContentScope.php
src/Http/DataTables/Scopes/Filters/RegionScope.php
src/Http/DataTables/Scopes/Filters/SystemScope.php
src/Http/DataTables/Tools/MoonsDataTable.php
src/resources/views/tools/moons/filters/moon-filter.blade.php
src/resources/views/tools/moons/list.blade.php

As per slack:
- Split `MoonScope` into `RegionScope`, `ConstellationScope`, `SystemScope`, and `MoonContentScope` 
- Removed the null checking needed in MoonsController by removing type specificity in scope constructors
- Middleware path should be fixed.
- StyleCI changes should be applied
- Fixed issues with missing reprocessing and price code I believe (git issue)

Moon Reporter Changes

---

src/Http/Composers/Esi.php
src/Http/Composers/User.php
src/Http/Controllers/Character/IntelController.php
src/Http/Controllers/Character/MailController.php
src/Http/Controllers/Character/PiController.php
src/Http/Controllers/Character/SkillsController.php
src/Http/Controllers/Character/WalletController.php
src/Http/Controllers/Configuration/AccessController.php
src/Http/Controllers/Configuration/SecurityController.php
src/Http/Controllers/Configuration/UserController.php
src/Http/Controllers/Corporation/ExtractionController.php
src/Http/Controllers/Corporation/LedgerController.php
src/Http/Controllers/Corporation/MiningLedgerController.php
src/Http/Controllers/Corporation/SecurityController.php
src/Http/Controllers/Corporation/StarbaseController.php
src/Http/Controllers/Corporation/StructureController.php
src/Http/Controllers/Corporation/SummaryController.php
src/Http/Controllers/Corporation/TrackingController.php
src/Http/Controllers/Corporation/WalletController.php
src/Http/Controllers/HomeController.php
src/Http/Controllers/Profile/ProfileController.php
src/Http/Controllers/Support/SearchController.php
src/Http/Controllers/Tools/StandingsController.php
src/Http/Validation/StandingsExistingElementAdd.php
src/Models/User.php
src/Traits/Stats.php

this allow to generate a valid dependencies tree.
depends on eveseat/services#130

refactor: move repositories from services package

---

src/Acl/Policies/AbstractPolicy.php
src/Acl/Policies/SquadPolicy.php
src/Http/Controllers/HomeController.php
src/Http/Controllers/Squads/MembersController.php
src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Home.php
src/Http/Routes/Squads/Routes.php
src/WebServiceProvider.php
src/resources/views/character/intel/journaldetail.blade.php
src/resources/views/character/partials/delete.blade.php
src/resources/views/common/minings/buttons/details.blade.php
src/resources/views/partials/maincharacter.blade.php
src/resources/views/squads/buttons/squads/kick.blade.php

Fix gate issue with squads.kick and unauthorized event

---

src/Http/Controllers/Auth/LoginController.php
src/Http/Controllers/Configuration/SeatController.php
src/WebServiceProvider.php
src/resources/views/configuration/sso/view.blade.php

Configuration related to ESI will now be available inside `SEAT_PATH/config/esi.php` and a new tag will be available (`seat`) - allowing to publish certain part of the project.
This will avoid to use `php artisan vendor:publish --all` :)
Special thanks to @wfjsw which point me to that workflow.

Publish certain configurations files - allowing more customizations

---

src/Config/seat-queues.php
src/WebServiceProvider.php

remove hardcode related to horizon pool configuration in web provider and use a dynamic configuration file that will be merged in proper place.

feat: ensure queue configuration is customizable

---

src/Http/Controllers/Configuration/UserController.php
src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Configuration/User.php
src/Http/Validation/ReassignCharacter.php
src/resources/views/configuration/users/buttons/transfer.blade.php
src/resources/views/configuration/users/edit.blade.php
src/resources/views/configuration/users/modals/transfer/transfer.blade.php

when a character is transferred across accounts, we logs an event into security logs which will keep a track of action.

feat(users): restore ability to reassign a character to another account

---

src/Acl/Policies/SquadPolicy.php
src/Http/Controllers/Squads/SquadsController.php
tests/database/migrations/2020_05_07_134209_create_users_test_table.php
tests/database/migrations/2020_05_07_221807_create_character_infos_test_table.php
tests/database/migrations/2020_05_07_232847_create_refresh_tokens_test_table.php
tests/database/migrations/2020_05_08_085856_create_corporation_infos_test_table.php
tests/database/migrations/2020_05_08_090405_create_roles_test_table.php
tests/database/migrations/2020_05_08_090816_create_role_user_test_table.php
tests/database/migrations/2020_05_08_091654_create_permissions_test_table.php
tests/database/migrations/2020_05_08_091844_create_permission_role_test_table.php
tests/database/migrations/2020_05_09_151051_create_character_roles_test_table.php
tests/database/migrations/2020_06_20_165655_create_security_logs_test_table.php

Also, enforce name ordering to ensure consistency between requests.
This should closes eveseat/seat#622

fix(squads): base policy on instance relations instead model

---

src/database/migrations/2019_11_12_220840_drop_groups_table.php

this attend to remove exception which might be thrown during users upgrade.
we will attempt to fix its state as best as we can instead.

refactor(users): fix database instead spawning alerts

---

src/Http/DataTables/Corporation/Industrial/MiningDataTable.php
src/resources/lang/en/permissions.php

Fix missing translation strings and missed colon in data table

Fix missing translations

---

src/Http/Controllers/Character/MailController.php
src/resources/views/character/mail-timeline-read.blade.php
src/resources/views/character/mail.blade.php

- character mail timeline now functional and respects any given roles
- character mail view fixed for orphaned users

fix(mail): Mail Timeline and Character Mail

---

src/Http/Controllers/Auth/SsoController.php
src/Http/Controllers/Profile/ProfileController.php

fix(sso): use same scopes as already auth characters on linking flow

---

src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Support/FastLookup.php
src/Observers/CharacterTitleObserver.php
src/WebServiceProvider.php
src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php

Adding corp titles as a squad filter so you can auto assign groups to directors for example.

Adding corp titles as a squad filter

---

src/Http/DataTables/Squads/MembersDataTable.php

feat(squads): limit disclosed alts to moderators and upper

---

src/resources/views/common/mails/modals/read/content.blade.php

fix(mail): show recipient corporations

---

src/Http/DataTables/Squads/CandidatesDataTable.php
src/Http/DataTables/Squads/MembersDataTable.php
src/Http/DataTables/Squads/RolesDataTable.php
src/Http/DataTables/Squads/SquadsDataTable.php
src/resources/views/squads/show.blade.php

related to e65f89e316ef07f92e3804bf152f7464d8544a74

refactor(squads): switch table render to POST method

---

src/resources/lang/de/moons.php

Correct translation

---

src/Http/Controllers/Squads/SquadsController.php
src/Http/Validation/Squad.php

fix(squads): set description to be mandatory on update

---

src/resources/views/squads/show.blade.php

do not submit form if user hit add button from either members or roles list when no value has been selected.
Closes eveseat/seat#656

fix(squads): prevent empty form to be submitted

---

src/resources/views/character/mail.blade.php

fix(ui): limit mail list to shown character when no valid token is available

---

src/Http/DataTables/Squads/RolesDataTable.php

fix(ui): render permissions tags on squad roles entries

---

src/resources/views/character/sheet.blade.php

fix(ui): render skill queue in ascending order

---

src/Http/Controllers/Corporation/LedgerController.php

fix(query): enforce order on field in select statement

---

src/Http/DataTables/Common/Financial/AbstractWalletJournalDataTable.php
src/resources/views/common/wallets/journaltranstype.blade.php

feat(ui): add reason on wallet journals

---

src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Support/FastLookup.php
src/Models/Filterable.php
src/resources/views/components/filters/modals/filters/rule.blade.php
src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php

feat(squads): add ability to filter scope

---

src/resources/views/character/intel/notes.blade.php

fix(notes): ensure add note button is containing entity id

---

src/Http/Controllers/Character/IntelController.php
src/Http/Controllers/Tools/StandingsController.php
src/Http/DataTables/Scopes/Filters/StandingsProfileScope.php
src/Http/DataTables/Tools/StandingsDataTable.php
src/Models/StandingsProfile.php
src/Models/StandingsProfileStanding.php
src/database/migrations/2020_12_03_230358_add_category_to_standings_profile_standings_table.php
src/resources/views/tools/standings/edit.blade.php
src/resources/views/tools/standings/partials/delete_button.blade.php

Change database to add category to profile standing table
Add datatables to standings builder page
Change so that standing contacts are not reliant on UniverseNames table

Feature: Add Alliance Contacts to Standings Builder

---

src/Http/Validation/ProfileSettings.php

fix: remove main character from profile validation

---

src/resources/views/character/assets/assets.blade.php
src/resources/views/character/blueprint.blade.php
src/resources/views/character/bookmarks.blade.php
src/resources/views/character/calendar.blade.php
src/resources/views/character/contacts.blade.php
src/resources/views/character/contracts.blade.php
src/resources/views/character/fittings.blade.php
src/resources/views/character/industry.blade.php
src/resources/views/character/killmails.blade.php
src/resources/views/character/mail.blade.php
src/resources/views/character/market.blade.php
src/resources/views/character/mining-ledger.blade.php
src/resources/views/character/notifications.blade.php
src/resources/views/character/pi.blade.php
src/resources/views/character/research.blade.php
src/resources/views/character/sheet.blade.php
src/resources/views/character/skills.blade.php
src/resources/views/character/standings.blade.php
src/resources/views/character/wallet/journal/journal.blade.php
src/resources/views/character/wallet/transactions/transactions.blade.php

feat: disable refresh button on expired token

---

src/resources/lang/en/wallet.php

fix: add new ess transfer entry

---

src/Acl/Policies/CharacterPolicy.php
src/Acl/Policies/CorporationPolicy.php
src/Http/DataTables/Scopes/CharacterScope.php
src/Http/DataTables/Scopes/CorporationScope.php
tests/database/migrations/2020_11_30_155457_create_corporation_roles_test_table.php

Also allow directors to access the characters pages of the corporation and the corporation page itself.

Allow CEO and Directors to get a list of characters and corporations

---

src/Http/Controllers/Corporation/TrackingController.php
src/Http/DataTables/Character/CharacterDataTable.php
src/Http/DataTables/Corporation/Intel/MembersTrackingDataTable.php
src/Http/DataTables/Scopes/Filters/TokenStatusScope.php
src/Http/Routes/Corporation/View.php
src/resources/lang/en/seat.php
src/resources/views/character/includes/summary.blade.php
src/resources/views/character/partials/token_status.blade.php
src/resources/views/corporation/layouts/view.blade.php
src/resources/views/corporation/tracking.blade.php
src/resources/views/partials/alliance.blade.php

same token status indicator is used for character summary and corporation tracking.
it is also added to the characters list.
corporation member tracking has been revamp to match with new design and benefits of the dynamic filter system.
Closes eveseat/seat#726

refactor: use new generic token status indicator

---

src/Http/Controllers/Support/SearchController.php
src/Http/DataTables/Character/Intel/Assets/Columns/Station.php
src/resources/views/search/components/character_assets.blade.php

fix(search): apply same logic than character assets to determine a location

---

src/Http/Controllers/Support/InsuranceController.php

fix: prevent invalid ship to throw an exception on render

---

src/Models/User.php
src/Observers/RefreshTokenObserver.php

This modification depends on eveseat/console#90

Refactor bus usage

---

src/Http/Controllers/Configuration/SeatController.php
src/Http/Controllers/Profile/ProfileController.php
src/Http/Routes/Profile/View.php
src/Http/Validation/SeatSettings.php
src/resources/lang/en/seat.php
src/resources/views/configuration/settings/view.blade.php
src/resources/views/profile/buttons/unlink.blade.php
src/resources/views/profile/view.blade.php

feat: allow end user to unlink characters themself

---

src/Http/DataTables/Scopes/Filters/TokenStatusScope.php
src/resources/views/common/fittings/modals/insurances/insurances.blade.php

fix(tracking): ensure default filter show both valid and invalid tokens

---

src/resources/views/corporation/extraction/partials/card-body.blade.php
src/resources/views/tools/moons/list.blade.php

Correct spelling for Gas

---

src/Models/Squads/SquadMember.php
src/Observers/SquadMemberObserver.php

fix(squads): fix reverse member relationship (pivot)

---

src/Http/DataTables/Configuration/UsersDataTable.php
src/resources/lang/en/seat.php
src/resources/views/character/includes/summary.blade.php
src/resources/views/configuration/users/edit.blade.php

- add user link on character summary
- add user creation date on user list
- add user creation date on user card

improve character/user accessibility and tracking

---

src/Http/Controllers/Corporation/ExtractionController.php
src/resources/css/skins/jet.css
src/resources/views/corporation/extraction/partials/card-body.blade.php

feat: add structure name on extractions

---

src/resources/views/includes/header.blade.php

Never in my life have I meant to navigate away from seat when visiting horizon

Open links to horizon queue in a new tab

---

src/resources/views/corporation/extraction/partials/card-body.blade.php

Change Gas Extraction Label to R4 based on market group id

Change Gas Extraction Label to R4

---

src/resources/views/about/partials/contacts.blade.php
src/resources/views/about/partials/disclaimer.blade.php
src/resources/views/about/partials/licences.blade.php
src/resources/views/includes/footer.blade.php

Update links to open in new tab

Link update

---

src/resources/js/seat.js
src/resources/views/squads/buttons/application/reject.blade.php

Corrects form not posting action after confirming action

Correct form for confirmform

---

src/Traits/Stats.php

Was testing with the updated home page changes and found this bug.

Correct path for CharacterWallet Journal class

---

src/Traits/Stats.php

add date filter to limit stats to active month

fix: reduce ratting stats to current month

---

src/Http/DataTables/Corporation/Intel/MembersTrackingDataTable.php
src/Http/DataTables/Exports/MembersTrackingDataTableExport.php
src/Http/Routes/Corporation/View.php
src/resources/views/character/partials/token_status.blade.php
src/resources/views/corporation/tracking.blade.php

Allows you to download the list at `/corporations/{id}/tracking`

Add download buttons for token tracking

---

src/Traits/Stats.php

Adding `corporate_reward_payout` in the sum of Ratted ISK. This brings in payments from Pochven sites and such.

Add corporate_reward_payout

---

src/resources/views/about/about.blade.php
src/resources/views/about/partials/contacts.blade.php
src/resources/views/about/partials/disclaimer.blade.php
src/resources/views/about/partials/donate.blade.php
src/resources/views/about/partials/licences.blade.php
src/resources/views/about/partials/security.blade.php

ui(licenses): update rendering for tabler template

---

src/resources/views/includes/header.blade.php
src/resources/views/partials/user-icon.blade.php
src/resources/views/partials/user.blade.php

Admin avatar shows as broken as there is no character portrait for character ID 0. Now for admin we use the SeAT logo.

ui: admin avatar should be seat logo

---

src/resources/views/configuration/schedule/view.blade.php

Updates the schedule list card, as well as the selects from Select2 to TomSelect on the Configuration Schedule page.

ui: update schedule page to 5.0.x

---

composer.json
src/Config/package.sidebar.php
src/Http/Routes/Configuration/Seat.php
src/Http/Routes/Configuration/Security.php
src/WebServiceProvider.php
src/resources/lang/en/seat.php
src/resources/views/configuration/security/logs.blade.php

in order to improve accessibility to admin tasks, add logs-viewer package to give access to logs using UI.
https://arunas.dev/log-viewer-for-laravel/

feat(ui): add logs-viewer

---

src/resources/views/character/includes/summary.blade.php

link is no longer pilot\character_name but rather character\character_id

Use character ID instead of name

---

.gitignore
src/Http/Controllers/Character/IntelController.php

fixes https://github.com/eveseat/seat/issues/900

Fix intel page error

---

composer.json
src/database/seeders/ScheduleSeeder.php

- This PR improves schedule seeding using the helper introduced here: https://github.com/eveseat/services/pull/179
- This other PR is required before this can be merged
- After the other PR is merged and released, we should bump the minimal services version of web

improve schedule seeder

---

src/resources/views/squads/create.blade.php
src/resources/views/squads/edit.blade.php

fix courtesy of @recursivetree.
closes eveseat/seat#909

fix: typo in squad creation

---

src/resources/views/character/includes/summary.blade.php

Fixes https://github.com/eveseat/seat/issues/903

fix zkillboard link on character sheet

---

src/Http/DataTables/Squads/MembersDataTable.php
src/resources/views/squads/show.blade.php

Closes https://github.com/eveseat/seat/issues/891

fix: squad member sort asc

---

src/resources/views/squads/show.blade.php

Closes https://github.com/eveseat/seat/issues/890

fix: squad delete confirmation

---

src/Http/Controllers/Configuration/UserController.php

Closes https://github.com/eveseat/seat/issues/826

fix: allow reassign with trashed token

---

composer.json
src/Config/web.characterfilter.php
src/Http/Controllers/Support/FastLookupController.php
src/Http/Routes/Support/FastLookup.php
tests/Squads/FactionRuleTest.php

Depends on: https://github.com/eveseat/eveapi/pull/417
Closes https://github.com/eveseat/seat/issues/829

feat: add faction squad filter

---

src/Http/Controllers/Configuration/SeatController.php

Reverts eveseat/web#696
See https://github.com/eveseat/eveapi/pull/423

Revert "feat: contact email change restart warning"
